services:
    php:
        build: ./docker/php
        container_name: carapi-php
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html:cached
        environment:
            - COMPOSER_ALLOW_SUPERUSER=1
        depends_on:
            - db

    nginx:
        image: nginx:1.25-alpine
        container_name: carapi-nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html:cached
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php

    db:
        image: mariadb:11.3
        container_name: carapi-db
        environment:
            - MARIADB_ROOT_PASSWORD=root
            - MARIADB_DATABASE=carapi
            - MARIADB_USER=root
            - MARIADB_PASSWORD=root
        ports:
            - "3307:3306"
        volumes:
            - dbdata:/var/lib/mysql

    adminer:
        image: adminer
        container_name: carapi-adminer
        restart: always
        ports:
            - "8081:8080"
        depends_on:
            - db

volumes:
    dbdata:
